### ISSUE TITLE
[Question] "Programmatically" spawning tasks without going through Telescope

### ISSUE THREAD

**Issue by ejmastnak** [jedrzejboczar/toggletasks.nvim#12]
Hi @jedrzejboczar, would you mind pointing me in the right direction for solving the following?
(Apologies if I have missed something obvious in the documentation.)

### Goal

Say I have the following `.toggletasks.json` file:

```json
{
    "tasks": [
        {
            "name": "FooTask",
            "cmd": "echo 'Hello from FooTask!'"
        }
    ]
}
```

Is it possible to spawn `FooTask` "programmatically", with a Lua command along the lines of e.g.

```lua
-- (Just to (hopefully) get the point across, of course this doesn't work at the moment)
-- The idea is to search for a task by `name` (in situations where we can count
-- on a task with the given `name` value being defined).
require('toggletasks').spawn_task_by_name('FooTask')
```

...and bypass the Telescope UI process of `:Telescope toggletasks spawn` > `FooTask` > `<Return>`?

### Use case

For many projects I *know* I will have a task named `FooTask` defined, and want to define a keymap to efficiently call `require('toggletasks').spawn_task_by_name('FooTask')`; this saves the repetitive task of going through Telescope's UI every time.
(Of course this is only a few keystrokes, but I am looking to optimizing repetitive tasks if possible.)

Thank you for your time and for the great plugin!

**Comment by jedrzejboczar** [comment]
Hi, there is no spawn_by_name function, but you can use the `discovery.lua` module to get a list of tasks and filter by name, for example:
```lua
local discovery = require('toggletasks.discovery')
local function spawn_by_name(name)
    -- discovery.tasks() returns a TaskQuery which is a list of tasks with some helper methods
    local tasks = discovery.tasks():filter(function(task)
        return task.config.name == name
    end)
    if #tasks > 0 then -- If any tasks found
        tasks[1]:spawn()
    end
end
spawn_by_name('FooTask')
```

**Comment by ejmastnak** [comment]
Thank you for the fast reply and solution! The `spawn_by_name` function finds tasks and spawns them just like I was hoping for.

If I may bother you with one more question, the ToggleTerm terminal does not become visible when spawning tasks with the provided `spawn_by_name` function (although the task *does* successfuly run).

After looking a little further, I see the terminal opens in a hidden (`h`) Vim buffer for tasks spawned with `spawn_by_name` and an active (`a`) buffer for tasks spawned by Telescope.

For example:

```bash
# Spawned with `discovery` and `spawn_by_name`; terminal buffer is hidden
:ls!
2u hF  "term://~/tmp/toggle-tasks//71868:echo 'Current file = /home/ej/tmp/toggle-tasks/test.txt';#toggleterm#1" line 0

# Spawned with Telescope; terminal buffer is active
:ls!
9u aF  "term://~/tmp/toggle-tasks//71688:echo 'Current file = /home/ej/tmp/toggle-tasks/test.txt';#toggleterm#1" line 0
```

Do you know how to make `spawn_by_name` open an active terminal buffer, so that a user can see the terminal and the task's output? In principle one could manually switch with `:buffer n`, but this is a bit inconvenient.

For what it's worth, I tried experimenting with `"hidden": false` and this does not seem to do the trick.

## Possibly relevant debug info:

From setting `debug = true` in `require('toggletasks').setup`

### Using `discovery` and `spawn_by_name`

```bash
from_config: parsing 1: {
  cmd = "echo 'Current file = ${file}'",
  hidden = false,
  name = "FooTask"

expand_vars: "echo 'Current file = ${file}'" -> { "echo 'Current file = ", "/home/ej/tmp/toggle-tasks/test.txt", "'" }

Task:spawn: with opts: {
  close_on_exit = false,
  cmd = "echo 'Current file = /home/ej/tmp/toggle-tasks/test.txt'",
  hidden = false
}

Task:spawn: task "/home/ej/tmp/toggle-tasks/.toggletasks.json#FooTask" in term "1"
```

Resulting buffer

```bash
:ls!
2u hF  "term://~/tmp/toggle-tasks//71868:echo 'Current file = /home/ej/tmp/toggle-tasks/test.txt';#toggleterm#1" line 0
```


### Using Telescope

```bash
from_config: parsing 1: {
  cmd = "echo 'Current file = ${file}'",
  hidden = false,
  name = "FooTask"

expand_vars: "echo 'Current file = ${file}'" -> { "echo 'Current file = ", "/home/ej/tmp/toggle-tasks/test.txt", "'" }

Task:spawn: with opts: {
  close_on_exit = false,
  cmd = "echo 'Current file = /home/ej/tmp/toggle-tasks/test.txt'",
  hidden = false
}

Task:spawn: task "/home/ej/tmp/toggle-tasks/.toggletasks.json#FooTask" in term "1"
```

Resulting buffer:

```bash
:ls!
9u aF  "term://~/tmp/toggle-tasks//71688:echo 'Current file = /home/ej/tmp/toggle-tasks/test.txt';#toggleterm#1" line 0
```

**Comment by ejmastnak** [comment]
Perfect! `task.term:open()` does the trick. Also appreciate the helpful references to source code.

Thanks for the plugin!
