### ISSUE TITLE
autodetect language specific tasks (npm, etc.)

### ISSUE THREAD

**Issue by redxtech** [jedrzejboczar/toggletasks.nvim#16]
this is a great plugin, but it's missing a crucial feature in my opinion: automatically parsing tasks from language specific files.

**node projects:** `package.json` has a `scripts` field that defines tasks to be run
**deno projects:** `deno.json` has a `tasks` field
**rust projects:** rust projects (containing a `cargo.toml`) always have a few tasks available, such as `cargo build`

**potential config options:**
`ignoreDependants`: for node projects, you can make a script such as `start`, `prestart`, and `poststart`. if `start` is called, `prestart` and `poststart` will be called before and after the `start` script respectively. this could allow these tasks to be ignored, as displaying them in the ui would be redundant

`nodeRunner`: for node projects you can use multiple package manager, such as `npm`, `yarn`, `pnpm`, etc. this could allow the user to specify their runner of choice

if you would be open to this, let me know.

thanks!

**Comment by redxtech** [comment]
it looks as though there are other options out there that accomplish this, so if it's outside the scope if this plugin that's all good as well

**Comment by jedrzejboczar** [comment]
Hi, to be fair I've recently stumbled upon [overseer.nvim](https://github.com/stevearc/overseer.nvim) and I'll probably switch to it as it is much more feature-complete and imo it's currently the best task runner for Neovim that I know of. 

Implementing and maintaining automatic task runners for different languages seems like a big thing and it's probably out of scope for toggletasks.nvim (especially as I'm slowly transitioning to overseer.nvim myself). I think that toggletasks.nvim is still viable option for some people as it uses somewhat different approach and is more minimalistic, but if someone needs more features than I'd recommend trying overseer.nvim.

Just to be clear, I think I'll be still maintaining this plugin and if someone is willing to add more features than I'll be happy to merge the PRs, but at the same time I probably won't be adding new features to toggletasks.nvim myself.

**Comment by redxtech** [comment]
Overseer was exactly the one I was referring to when I mentioned other options that I accomplish this!

**Comment by Zeioth** [comment]
Overseer is way harder to setup though. After 1 hour tweaking I've been unable to create a task that run 2 comands. On toggletask took me 5 minutes to achieve that same thing.
