### ISSUE TITLE
after update toggleterm, toggletasks is broken

### ISSUE THREAD

**Issue by qixiao986** [jedrzejboczar/toggletasks.nvim#2]
[refactor(terminal): use nvim_create_autocmd](https://github.com/akinsho/toggleterm.nvim/commit/9563a9fac8e36a6f2545732acac5b2935872db66) after toggleterm's this commit, toggletasks is broken. When I first open telescope list, it works fine, but when I open it again, it reports error.
![output](https://user-images.githubusercontent.com/3962171/170900109-275565ca-70ab-42a6-b636-b11f75349c3c.gif)

**Comment by jedrzejboczar** [comment]
Thanks for the report and identifying the commit. This should now be fixed in https://github.com/jedrzejboczar/toggletasks.nvim/commit/c1b932a72acffe4a8cc4c79aa0bb946c680eda35.
